namespace Nhom5_TVThinhNHQHuyPNTanDVDucTNQuynh_LTNet
{
    partial class Dashboard
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Dashboard));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges8 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.usrName = new Bunifu.UI.WinForms.BunifuLabel();
            this.mainPanel = new Bunifu.UI.WinForms.BunifuPanel();
            this.bunifuPanel1 = new Bunifu.UI.WinForms.BunifuPanel();
            this.thongTinNhom = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.thongKeBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.hoaDonBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.loaiHangBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.hangHoaBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.qlkhBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuButton1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.qlmk = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuPanel1.SuspendLayout();
            this.SuspendLayout();
            // 
            // usrName
            // 
            this.usrName.AllowParentOverrides = false;
            this.usrName.AutoEllipsis = false;
            this.usrName.Cursor = System.Windows.Forms.Cursors.Default;
            this.usrName.CursorType = System.Windows.Forms.Cursors.Default;
            this.usrName.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.usrName.Location = new System.Drawing.Point(192, 22);
            this.usrName.Name = "usrName";
            this.usrName.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.usrName.Size = new System.Drawing.Size(84, 15);
            this.usrName.TabIndex = 1;
            this.usrName.Text = "Tên người dùng";
            this.usrName.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.usrName.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // mainPanel
            // 
            this.mainPanel.BackgroundColor = System.Drawing.Color.Transparent;
            this.mainPanel.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("mainPanel.BackgroundImage")));
            this.mainPanel.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.mainPanel.BorderColor = System.Drawing.Color.Transparent;
            this.mainPanel.BorderRadius = 3;
            this.mainPanel.BorderThickness = 1;
            this.mainPanel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.mainPanel.Location = new System.Drawing.Point(250, 0);
            this.mainPanel.Name = "mainPanel";
            this.mainPanel.ShowBorders = false;
            this.mainPanel.Size = new System.Drawing.Size(884, 451);
            this.mainPanel.TabIndex = 5;
            // 
            // bunifuPanel1
            // 
            this.bunifuPanel1.BackgroundColor = System.Drawing.Color.Transparent;
            this.bunifuPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel1.BackgroundImage")));
            this.bunifuPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel1.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel1.BorderRadius = 3;
            this.bunifuPanel1.BorderThickness = 1;
            this.bunifuPanel1.Controls.Add(this.thongTinNhom);
            this.bunifuPanel1.Controls.Add(this.qlmk);
            this.bunifuPanel1.Controls.Add(this.thongKeBtn);
            this.bunifuPanel1.Controls.Add(this.hoaDonBtn);
            this.bunifuPanel1.Controls.Add(this.loaiHangBtn);
            this.bunifuPanel1.Controls.Add(this.hangHoaBtn);
            this.bunifuPanel1.Controls.Add(this.qlkhBtn);
            this.bunifuPanel1.Controls.Add(this.bunifuButton1);
            this.bunifuPanel1.Dock = System.Windows.Forms.DockStyle.Left;
            this.bunifuPanel1.Location = new System.Drawing.Point(0, 0);
            this.bunifuPanel1.Name = "bunifuPanel1";
            this.bunifuPanel1.ShowBorders = false;
            this.bunifuPanel1.Size = new System.Drawing.Size(250, 451);
            this.bunifuPanel1.TabIndex = 1;
            // 
            // thongTinNhom
            // 
            this.thongTinNhom.AllowAnimations = true;
            this.thongTinNhom.AllowMouseEffects = true;
            this.thongTinNhom.AllowToggling = false;
            this.thongTinNhom.AnimationSpeed = 200;
            this.thongTinNhom.AutoGenerateColors = false;
            this.thongTinNhom.AutoRoundBorders = false;
            this.thongTinNhom.AutoSizeLeftIcon = true;
            this.thongTinNhom.AutoSizeRightIcon = true;
            this.thongTinNhom.BackColor = System.Drawing.Color.Transparent;
            this.thongTinNhom.BackColor1 = System.Drawing.Color.Transparent;
            this.thongTinNhom.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("thongTinNhom.BackgroundImage")));
            this.thongTinNhom.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.thongTinNhom.ButtonText = "Thông tin";
            this.thongTinNhom.ButtonTextMarginLeft = 0;
            this.thongTinNhom.ColorContrastOnClick = 45;
            this.thongTinNhom.ColorContrastOnHover = 45;
            this.thongTinNhom.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.thongTinNhom.CustomizableEdges = borderEdges1;
            this.thongTinNhom.DialogResult = System.Windows.Forms.DialogResult.None;
            this.thongTinNhom.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.thongTinNhom.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.thongTinNhom.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.thongTinNhom.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.thongTinNhom.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.thongTinNhom.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(62)))), ((int)(((byte)(80)))));
            this.thongTinNhom.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.thongTinNhom.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.thongTinNhom.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.thongTinNhom.IconMarginLeft = 11;
            this.thongTinNhom.IconPadding = 10;
            this.thongTinNhom.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.thongTinNhom.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.thongTinNhom.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.thongTinNhom.IconSize = 25;
            this.thongTinNhom.IdleBorderColor = System.Drawing.Color.Transparent;
            this.thongTinNhom.IdleBorderRadius = 16;
            this.thongTinNhom.IdleBorderThickness = 1;
            this.thongTinNhom.IdleFillColor = System.Drawing.Color.Transparent;
            this.thongTinNhom.IdleIconLeftImage = null;
            this.thongTinNhom.IdleIconRightImage = null;
            this.thongTinNhom.IndicateFocus = false;
            this.thongTinNhom.Location = new System.Drawing.Point(12, 67);
            this.thongTinNhom.Name = "thongTinNhom";
            this.thongTinNhom.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.thongTinNhom.OnDisabledState.BorderRadius = 16;
            this.thongTinNhom.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.thongTinNhom.OnDisabledState.BorderThickness = 0;
            this.thongTinNhom.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.thongTinNhom.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.thongTinNhom.OnDisabledState.IconLeftImage = null;
            this.thongTinNhom.OnDisabledState.IconRightImage = null;
            this.thongTinNhom.onHoverState.BorderColor = System.Drawing.Color.Transparent;
            this.thongTinNhom.onHoverState.BorderRadius = 16;
            this.thongTinNhom.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.thongTinNhom.onHoverState.BorderThickness = 0;
            this.thongTinNhom.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(244)))), ((int)(((byte)(247)))), ((int)(((byte)(248)))));
            this.thongTinNhom.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(62)))), ((int)(((byte)(80)))));
            this.thongTinNhom.onHoverState.IconLeftImage = null;
            this.thongTinNhom.onHoverState.IconRightImage = null;
            this.thongTinNhom.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.thongTinNhom.OnIdleState.BorderRadius = 16;
            this.thongTinNhom.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.thongTinNhom.OnIdleState.BorderThickness = 0;
            this.thongTinNhom.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.thongTinNhom.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(62)))), ((int)(((byte)(80)))));
            this.thongTinNhom.OnIdleState.IconLeftImage = null;
            this.thongTinNhom.OnIdleState.IconRightImage = null;
            this.thongTinNhom.OnPressedState.BorderColor = System.Drawing.Color.Transparent;
            this.thongTinNhom.OnPressedState.BorderRadius = 16;
            this.thongTinNhom.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.thongTinNhom.OnPressedState.BorderThickness = 0;
            this.thongTinNhom.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(244)))), ((int)(((byte)(247)))), ((int)(((byte)(248)))));
            this.thongTinNhom.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(62)))), ((int)(((byte)(80)))));
            this.thongTinNhom.OnPressedState.IconLeftImage = null;
            this.thongTinNhom.OnPressedState.IconRightImage = null;
            this.thongTinNhom.Size = new System.Drawing.Size(224, 34);
            this.thongTinNhom.TabIndex = 4;
            this.thongTinNhom.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.thongTinNhom.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.thongTinNhom.TextMarginLeft = 0;
            this.thongTinNhom.TextPadding = new System.Windows.Forms.Padding(20, 0, 0, 0);
            this.thongTinNhom.UseDefaultRadiusAndThickness = true;
            this.thongTinNhom.Click += new System.EventHandler(this.thongTinNhom_Click);
            // 
            // thongKeBtn
            // 
            this.thongKeBtn.AllowAnimations = true;
            this.thongKeBtn.AllowMouseEffects = true;
            this.thongKeBtn.AllowToggling = false;
            this.thongKeBtn.AnimationSpeed = 200;
            this.thongKeBtn.AutoGenerateColors = false;
            this.thongKeBtn.AutoRoundBorders = false;
            this.thongKeBtn.AutoSizeLeftIcon = true;
            this.thongKeBtn.AutoSizeRightIcon = true;
            this.thongKeBtn.BackColor = System.Drawing.Color.Transparent;
            this.thongKeBtn.BackColor1 = System.Drawing.Color.Transparent;
            this.thongKeBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("thongKeBtn.BackgroundImage")));
            this.thongKeBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.thongKeBtn.ButtonText = "Quản lý thống kê";
            this.thongKeBtn.ButtonTextMarginLeft = 0;
            this.thongKeBtn.ColorContrastOnClick = 45;
            this.thongKeBtn.ColorContrastOnHover = 45;
            this.thongKeBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.thongKeBtn.CustomizableEdges = borderEdges3;
            this.thongKeBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.thongKeBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.thongKeBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.thongKeBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.thongKeBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.thongKeBtn.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.thongKeBtn.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(62)))), ((int)(((byte)(80)))));
            this.thongKeBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.thongKeBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.thongKeBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.thongKeBtn.IconMarginLeft = 11;
            this.thongKeBtn.IconPadding = 10;
            this.thongKeBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.thongKeBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.thongKeBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.thongKeBtn.IconSize = 25;
            this.thongKeBtn.IdleBorderColor = System.Drawing.Color.Transparent;
            this.thongKeBtn.IdleBorderRadius = 16;
            this.thongKeBtn.IdleBorderThickness = 1;
            this.thongKeBtn.IdleFillColor = System.Drawing.Color.Transparent;
            this.thongKeBtn.IdleIconLeftImage = null;
            this.thongKeBtn.IdleIconRightImage = null;
            this.thongKeBtn.IndicateFocus = false;
            this.thongKeBtn.Location = new System.Drawing.Point(12, 267);
            this.thongKeBtn.Name = "thongKeBtn";
            this.thongKeBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.thongKeBtn.OnDisabledState.BorderRadius = 16;
            this.thongKeBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.thongKeBtn.OnDisabledState.BorderThickness = 0;
            this.thongKeBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.thongKeBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.thongKeBtn.OnDisabledState.IconLeftImage = null;
            this.thongKeBtn.OnDisabledState.IconRightImage = null;
            this.thongKeBtn.onHoverState.BorderColor = System.Drawing.Color.Transparent;
            this.thongKeBtn.onHoverState.BorderRadius = 16;
            this.thongKeBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.thongKeBtn.onHoverState.BorderThickness = 0;
            this.thongKeBtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(244)))), ((int)(((byte)(247)))), ((int)(((byte)(248)))));
            this.thongKeBtn.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(62)))), ((int)(((byte)(80)))));
            this.thongKeBtn.onHoverState.IconLeftImage = null;
            this.thongKeBtn.onHoverState.IconRightImage = null;
            this.thongKeBtn.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.thongKeBtn.OnIdleState.BorderRadius = 16;
            this.thongKeBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.thongKeBtn.OnIdleState.BorderThickness = 0;
            this.thongKeBtn.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.thongKeBtn.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(62)))), ((int)(((byte)(80)))));
            this.thongKeBtn.OnIdleState.IconLeftImage = null;
            this.thongKeBtn.OnIdleState.IconRightImage = null;
            this.thongKeBtn.OnPressedState.BorderColor = System.Drawing.Color.Transparent;
            this.thongKeBtn.OnPressedState.BorderRadius = 16;
            this.thongKeBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.thongKeBtn.OnPressedState.BorderThickness = 0;
            this.thongKeBtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(244)))), ((int)(((byte)(247)))), ((int)(((byte)(248)))));
            this.thongKeBtn.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(62)))), ((int)(((byte)(80)))));
            this.thongKeBtn.OnPressedState.IconLeftImage = null;
            this.thongKeBtn.OnPressedState.IconRightImage = null;
            this.thongKeBtn.Size = new System.Drawing.Size(224, 34);
            this.thongKeBtn.TabIndex = 3;
            this.thongKeBtn.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.thongKeBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.thongKeBtn.TextMarginLeft = 0;
            this.thongKeBtn.TextPadding = new System.Windows.Forms.Padding(20, 0, 0, 0);
            this.thongKeBtn.UseDefaultRadiusAndThickness = true;
            this.thongKeBtn.Click += new System.EventHandler(this.qltk_Click);
            // 
            // hoaDonBtn
            // 
            this.hoaDonBtn.AllowAnimations = true;
            this.hoaDonBtn.AllowMouseEffects = true;
            this.hoaDonBtn.AllowToggling = false;
            this.hoaDonBtn.AnimationSpeed = 200;
            this.hoaDonBtn.AutoGenerateColors = false;
            this.hoaDonBtn.AutoRoundBorders = false;
            this.hoaDonBtn.AutoSizeLeftIcon = true;
            this.hoaDonBtn.AutoSizeRightIcon = true;
            this.hoaDonBtn.BackColor = System.Drawing.Color.Transparent;
            this.hoaDonBtn.BackColor1 = System.Drawing.Color.Transparent;
            this.hoaDonBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("hoaDonBtn.BackgroundImage")));
            this.hoaDonBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.hoaDonBtn.ButtonText = "Quản lý hoá đơn";
            this.hoaDonBtn.ButtonTextMarginLeft = 0;
            this.hoaDonBtn.ColorContrastOnClick = 45;
            this.hoaDonBtn.ColorContrastOnHover = 45;
            this.hoaDonBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.hoaDonBtn.CustomizableEdges = borderEdges4;
            this.hoaDonBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.hoaDonBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.hoaDonBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.hoaDonBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.hoaDonBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.hoaDonBtn.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.hoaDonBtn.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(62)))), ((int)(((byte)(80)))));
            this.hoaDonBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.hoaDonBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.hoaDonBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.hoaDonBtn.IconMarginLeft = 11;
            this.hoaDonBtn.IconPadding = 10;
            this.hoaDonBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.hoaDonBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.hoaDonBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.hoaDonBtn.IconSize = 25;
            this.hoaDonBtn.IdleBorderColor = System.Drawing.Color.Transparent;
            this.hoaDonBtn.IdleBorderRadius = 16;
            this.hoaDonBtn.IdleBorderThickness = 1;
            this.hoaDonBtn.IdleFillColor = System.Drawing.Color.Transparent;
            this.hoaDonBtn.IdleIconLeftImage = null;
            this.hoaDonBtn.IdleIconRightImage = null;
            this.hoaDonBtn.IndicateFocus = false;
            this.hoaDonBtn.Location = new System.Drawing.Point(12, 227);
            this.hoaDonBtn.Name = "hoaDonBtn";
            this.hoaDonBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.hoaDonBtn.OnDisabledState.BorderRadius = 16;
            this.hoaDonBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.hoaDonBtn.OnDisabledState.BorderThickness = 0;
            this.hoaDonBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.hoaDonBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.hoaDonBtn.OnDisabledState.IconLeftImage = null;
            this.hoaDonBtn.OnDisabledState.IconRightImage = null;
            this.hoaDonBtn.onHoverState.BorderColor = System.Drawing.Color.Transparent;
            this.hoaDonBtn.onHoverState.BorderRadius = 16;
            this.hoaDonBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.hoaDonBtn.onHoverState.BorderThickness = 0;
            this.hoaDonBtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(244)))), ((int)(((byte)(247)))), ((int)(((byte)(248)))));
            this.hoaDonBtn.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(62)))), ((int)(((byte)(80)))));
            this.hoaDonBtn.onHoverState.IconLeftImage = null;
            this.hoaDonBtn.onHoverState.IconRightImage = null;
            this.hoaDonBtn.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.hoaDonBtn.OnIdleState.BorderRadius = 16;
            this.hoaDonBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.hoaDonBtn.OnIdleState.BorderThickness = 0;
            this.hoaDonBtn.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.hoaDonBtn.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(62)))), ((int)(((byte)(80)))));
            this.hoaDonBtn.OnIdleState.IconLeftImage = null;
            this.hoaDonBtn.OnIdleState.IconRightImage = null;
            this.hoaDonBtn.OnPressedState.BorderColor = System.Drawing.Color.Transparent;
            this.hoaDonBtn.OnPressedState.BorderRadius = 16;
            this.hoaDonBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.hoaDonBtn.OnPressedState.BorderThickness = 0;
            this.hoaDonBtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(244)))), ((int)(((byte)(247)))), ((int)(((byte)(248)))));
            this.hoaDonBtn.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(62)))), ((int)(((byte)(80)))));
            this.hoaDonBtn.OnPressedState.IconLeftImage = null;
            this.hoaDonBtn.OnPressedState.IconRightImage = null;
            this.hoaDonBtn.Size = new System.Drawing.Size(224, 34);
            this.hoaDonBtn.TabIndex = 3;
            this.hoaDonBtn.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.hoaDonBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.hoaDonBtn.TextMarginLeft = 0;
            this.hoaDonBtn.TextPadding = new System.Windows.Forms.Padding(20, 0, 0, 0);
            this.hoaDonBtn.UseDefaultRadiusAndThickness = true;
            this.hoaDonBtn.Click += new System.EventHandler(this.qlhd_Click);
            // 
            // loaiHangBtn
            // 
            this.loaiHangBtn.AllowAnimations = true;
            this.loaiHangBtn.AllowMouseEffects = true;
            this.loaiHangBtn.AllowToggling = false;
            this.loaiHangBtn.AnimationSpeed = 200;
            this.loaiHangBtn.AutoGenerateColors = false;
            this.loaiHangBtn.AutoRoundBorders = false;
            this.loaiHangBtn.AutoSizeLeftIcon = true;
            this.loaiHangBtn.AutoSizeRightIcon = true;
            this.loaiHangBtn.BackColor = System.Drawing.Color.Transparent;
            this.loaiHangBtn.BackColor1 = System.Drawing.Color.Transparent;
            this.loaiHangBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("loaiHangBtn.BackgroundImage")));
            this.loaiHangBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.loaiHangBtn.ButtonText = "Quản lý loại hàng";
            this.loaiHangBtn.ButtonTextMarginLeft = 0;
            this.loaiHangBtn.ColorContrastOnClick = 45;
            this.loaiHangBtn.ColorContrastOnHover = 45;
            this.loaiHangBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.loaiHangBtn.CustomizableEdges = borderEdges5;
            this.loaiHangBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.loaiHangBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.loaiHangBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.loaiHangBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.loaiHangBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.loaiHangBtn.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.loaiHangBtn.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(62)))), ((int)(((byte)(80)))));
            this.loaiHangBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.loaiHangBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.loaiHangBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.loaiHangBtn.IconMarginLeft = 11;
            this.loaiHangBtn.IconPadding = 10;
            this.loaiHangBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.loaiHangBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.loaiHangBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.loaiHangBtn.IconSize = 25;
            this.loaiHangBtn.IdleBorderColor = System.Drawing.Color.Transparent;
            this.loaiHangBtn.IdleBorderRadius = 16;
            this.loaiHangBtn.IdleBorderThickness = 1;
            this.loaiHangBtn.IdleFillColor = System.Drawing.Color.Transparent;
            this.loaiHangBtn.IdleIconLeftImage = null;
            this.loaiHangBtn.IdleIconRightImage = null;
            this.loaiHangBtn.IndicateFocus = false;
            this.loaiHangBtn.Location = new System.Drawing.Point(12, 187);
            this.loaiHangBtn.Name = "loaiHangBtn";
            this.loaiHangBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.loaiHangBtn.OnDisabledState.BorderRadius = 16;
            this.loaiHangBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.loaiHangBtn.OnDisabledState.BorderThickness = 0;
            this.loaiHangBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.loaiHangBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.loaiHangBtn.OnDisabledState.IconLeftImage = null;
            this.loaiHangBtn.OnDisabledState.IconRightImage = null;
            this.loaiHangBtn.onHoverState.BorderColor = System.Drawing.Color.Transparent;
            this.loaiHangBtn.onHoverState.BorderRadius = 16;
            this.loaiHangBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.loaiHangBtn.onHoverState.BorderThickness = 0;
            this.loaiHangBtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(244)))), ((int)(((byte)(247)))), ((int)(((byte)(248)))));
            this.loaiHangBtn.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(62)))), ((int)(((byte)(80)))));
            this.loaiHangBtn.onHoverState.IconLeftImage = null;
            this.loaiHangBtn.onHoverState.IconRightImage = null;
            this.loaiHangBtn.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.loaiHangBtn.OnIdleState.BorderRadius = 16;
            this.loaiHangBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.loaiHangBtn.OnIdleState.BorderThickness = 0;
            this.loaiHangBtn.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.loaiHangBtn.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(62)))), ((int)(((byte)(80)))));
            this.loaiHangBtn.OnIdleState.IconLeftImage = null;
            this.loaiHangBtn.OnIdleState.IconRightImage = null;
            this.loaiHangBtn.OnPressedState.BorderColor = System.Drawing.Color.Transparent;
            this.loaiHangBtn.OnPressedState.BorderRadius = 16;
            this.loaiHangBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.loaiHangBtn.OnPressedState.BorderThickness = 0;
            this.loaiHangBtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(244)))), ((int)(((byte)(247)))), ((int)(((byte)(248)))));
            this.loaiHangBtn.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(62)))), ((int)(((byte)(80)))));
            this.loaiHangBtn.OnPressedState.IconLeftImage = null;
            this.loaiHangBtn.OnPressedState.IconRightImage = null;
            this.loaiHangBtn.Size = new System.Drawing.Size(224, 34);
            this.loaiHangBtn.TabIndex = 3;
            this.loaiHangBtn.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.loaiHangBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.loaiHangBtn.TextMarginLeft = 0;
            this.loaiHangBtn.TextPadding = new System.Windows.Forms.Padding(20, 0, 0, 0);
            this.loaiHangBtn.UseDefaultRadiusAndThickness = true;
            this.loaiHangBtn.Click += new System.EventHandler(this.qllh_Click);
            // 
            // hangHoaBtn
            // 
            this.hangHoaBtn.AllowAnimations = true;
            this.hangHoaBtn.AllowMouseEffects = true;
            this.hangHoaBtn.AllowToggling = false;
            this.hangHoaBtn.AnimationSpeed = 200;
            this.hangHoaBtn.AutoGenerateColors = false;
            this.hangHoaBtn.AutoRoundBorders = false;
            this.hangHoaBtn.AutoSizeLeftIcon = true;
            this.hangHoaBtn.AutoSizeRightIcon = true;
            this.hangHoaBtn.BackColor = System.Drawing.Color.Transparent;
            this.hangHoaBtn.BackColor1 = System.Drawing.Color.Transparent;
            this.hangHoaBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("hangHoaBtn.BackgroundImage")));
            this.hangHoaBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.hangHoaBtn.ButtonText = "Quản lý hàng hoá";
            this.hangHoaBtn.ButtonTextMarginLeft = 0;
            this.hangHoaBtn.ColorContrastOnClick = 45;
            this.hangHoaBtn.ColorContrastOnHover = 45;
            this.hangHoaBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.hangHoaBtn.CustomizableEdges = borderEdges6;
            this.hangHoaBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.hangHoaBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.hangHoaBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.hangHoaBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.hangHoaBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.hangHoaBtn.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.hangHoaBtn.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(62)))), ((int)(((byte)(80)))));
            this.hangHoaBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.hangHoaBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.hangHoaBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.hangHoaBtn.IconMarginLeft = 11;
            this.hangHoaBtn.IconPadding = 10;
            this.hangHoaBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.hangHoaBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.hangHoaBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.hangHoaBtn.IconSize = 25;
            this.hangHoaBtn.IdleBorderColor = System.Drawing.Color.Transparent;
            this.hangHoaBtn.IdleBorderRadius = 16;
            this.hangHoaBtn.IdleBorderThickness = 1;
            this.hangHoaBtn.IdleFillColor = System.Drawing.Color.Transparent;
            this.hangHoaBtn.IdleIconLeftImage = null;
            this.hangHoaBtn.IdleIconRightImage = null;
            this.hangHoaBtn.IndicateFocus = false;
            this.hangHoaBtn.Location = new System.Drawing.Point(12, 147);
            this.hangHoaBtn.Name = "hangHoaBtn";
            this.hangHoaBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.hangHoaBtn.OnDisabledState.BorderRadius = 16;
            this.hangHoaBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.hangHoaBtn.OnDisabledState.BorderThickness = 0;
            this.hangHoaBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.hangHoaBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.hangHoaBtn.OnDisabledState.IconLeftImage = null;
            this.hangHoaBtn.OnDisabledState.IconRightImage = null;
            this.hangHoaBtn.onHoverState.BorderColor = System.Drawing.Color.Transparent;
            this.hangHoaBtn.onHoverState.BorderRadius = 16;
            this.hangHoaBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.hangHoaBtn.onHoverState.BorderThickness = 0;
            this.hangHoaBtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(244)))), ((int)(((byte)(247)))), ((int)(((byte)(248)))));
            this.hangHoaBtn.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(62)))), ((int)(((byte)(80)))));
            this.hangHoaBtn.onHoverState.IconLeftImage = null;
            this.hangHoaBtn.onHoverState.IconRightImage = null;
            this.hangHoaBtn.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.hangHoaBtn.OnIdleState.BorderRadius = 16;
            this.hangHoaBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.hangHoaBtn.OnIdleState.BorderThickness = 0;
            this.hangHoaBtn.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.hangHoaBtn.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(62)))), ((int)(((byte)(80)))));
            this.hangHoaBtn.OnIdleState.IconLeftImage = null;
            this.hangHoaBtn.OnIdleState.IconRightImage = null;
            this.hangHoaBtn.OnPressedState.BorderColor = System.Drawing.Color.Transparent;
            this.hangHoaBtn.OnPressedState.BorderRadius = 16;
            this.hangHoaBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.hangHoaBtn.OnPressedState.BorderThickness = 0;
            this.hangHoaBtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(244)))), ((int)(((byte)(247)))), ((int)(((byte)(248)))));
            this.hangHoaBtn.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(62)))), ((int)(((byte)(80)))));
            this.hangHoaBtn.OnPressedState.IconLeftImage = null;
            this.hangHoaBtn.OnPressedState.IconRightImage = null;
            this.hangHoaBtn.Size = new System.Drawing.Size(224, 34);
            this.hangHoaBtn.TabIndex = 3;
            this.hangHoaBtn.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.hangHoaBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.hangHoaBtn.TextMarginLeft = 0;
            this.hangHoaBtn.TextPadding = new System.Windows.Forms.Padding(20, 0, 0, 0);
            this.hangHoaBtn.UseDefaultRadiusAndThickness = true;
            this.hangHoaBtn.Click += new System.EventHandler(this.qlhh_Click);
            // 
            // qlkhBtn
            // 
            this.qlkhBtn.AllowAnimations = true;
            this.qlkhBtn.AllowMouseEffects = true;
            this.qlkhBtn.AllowToggling = false;
            this.qlkhBtn.AnimationSpeed = 200;
            this.qlkhBtn.AutoGenerateColors = false;
            this.qlkhBtn.AutoRoundBorders = false;
            this.qlkhBtn.AutoSizeLeftIcon = true;
            this.qlkhBtn.AutoSizeRightIcon = true;
            this.qlkhBtn.BackColor = System.Drawing.Color.Transparent;
            this.qlkhBtn.BackColor1 = System.Drawing.Color.Transparent;
            this.qlkhBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("qlkhBtn.BackgroundImage")));
            this.qlkhBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.qlkhBtn.ButtonText = "Quản lý khách hàng";
            this.qlkhBtn.ButtonTextMarginLeft = 0;
            this.qlkhBtn.ColorContrastOnClick = 45;
            this.qlkhBtn.ColorContrastOnHover = 45;
            this.qlkhBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.qlkhBtn.CustomizableEdges = borderEdges7;
            this.qlkhBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.qlkhBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.qlkhBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.qlkhBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.qlkhBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.qlkhBtn.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.qlkhBtn.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(62)))), ((int)(((byte)(80)))));
            this.qlkhBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.qlkhBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.qlkhBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.qlkhBtn.IconMarginLeft = 11;
            this.qlkhBtn.IconPadding = 10;
            this.qlkhBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.qlkhBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.qlkhBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.qlkhBtn.IconSize = 25;
            this.qlkhBtn.IdleBorderColor = System.Drawing.Color.Transparent;
            this.qlkhBtn.IdleBorderRadius = 16;
            this.qlkhBtn.IdleBorderThickness = 1;
            this.qlkhBtn.IdleFillColor = System.Drawing.Color.Transparent;
            this.qlkhBtn.IdleIconLeftImage = null;
            this.qlkhBtn.IdleIconRightImage = null;
            this.qlkhBtn.IndicateFocus = false;
            this.qlkhBtn.Location = new System.Drawing.Point(12, 107);
            this.qlkhBtn.Name = "qlkhBtn";
            this.qlkhBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.qlkhBtn.OnDisabledState.BorderRadius = 16;
            this.qlkhBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.qlkhBtn.OnDisabledState.BorderThickness = 0;
            this.qlkhBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.qlkhBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.qlkhBtn.OnDisabledState.IconLeftImage = null;
            this.qlkhBtn.OnDisabledState.IconRightImage = null;
            this.qlkhBtn.onHoverState.BorderColor = System.Drawing.Color.Transparent;
            this.qlkhBtn.onHoverState.BorderRadius = 16;
            this.qlkhBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.qlkhBtn.onHoverState.BorderThickness = 0;
            this.qlkhBtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(244)))), ((int)(((byte)(247)))), ((int)(((byte)(248)))));
            this.qlkhBtn.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(62)))), ((int)(((byte)(80)))));
            this.qlkhBtn.onHoverState.IconLeftImage = null;
            this.qlkhBtn.onHoverState.IconRightImage = null;
            this.qlkhBtn.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.qlkhBtn.OnIdleState.BorderRadius = 16;
            this.qlkhBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.qlkhBtn.OnIdleState.BorderThickness = 0;
            this.qlkhBtn.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.qlkhBtn.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(62)))), ((int)(((byte)(80)))));
            this.qlkhBtn.OnIdleState.IconLeftImage = null;
            this.qlkhBtn.OnIdleState.IconRightImage = null;
            this.qlkhBtn.OnPressedState.BorderColor = System.Drawing.Color.Transparent;
            this.qlkhBtn.OnPressedState.BorderRadius = 16;
            this.qlkhBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.qlkhBtn.OnPressedState.BorderThickness = 0;
            this.qlkhBtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(244)))), ((int)(((byte)(247)))), ((int)(((byte)(248)))));
            this.qlkhBtn.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(62)))), ((int)(((byte)(80)))));
            this.qlkhBtn.OnPressedState.IconLeftImage = null;
            this.qlkhBtn.OnPressedState.IconRightImage = null;
            this.qlkhBtn.Size = new System.Drawing.Size(224, 34);
            this.qlkhBtn.TabIndex = 3;
            this.qlkhBtn.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.qlkhBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.qlkhBtn.TextMarginLeft = 0;
            this.qlkhBtn.TextPadding = new System.Windows.Forms.Padding(20, 0, 0, 0);
            this.qlkhBtn.UseDefaultRadiusAndThickness = true;
            this.qlkhBtn.Click += new System.EventHandler(this.qlkh_Click);
            // 
            // bunifuButton1
            // 
            this.bunifuButton1.AllowAnimations = true;
            this.bunifuButton1.AllowMouseEffects = true;
            this.bunifuButton1.AllowToggling = false;
            this.bunifuButton1.Anchor = System.Windows.Forms.AnchorStyles.Bottom;
            this.bunifuButton1.AnimationSpeed = 200;
            this.bunifuButton1.AutoGenerateColors = false;
            this.bunifuButton1.AutoRoundBorders = false;
            this.bunifuButton1.AutoSizeLeftIcon = true;
            this.bunifuButton1.AutoSizeRightIcon = true;
            this.bunifuButton1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton1.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(25)))), ((int)(((byte)(91)))), ((int)(((byte)(255)))));
            this.bunifuButton1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton1.BackgroundImage")));
            this.bunifuButton1.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.ButtonText = "Đăng xuất";
            this.bunifuButton1.ButtonTextMarginLeft = 0;
            this.bunifuButton1.ColorContrastOnClick = 45;
            this.bunifuButton1.ColorContrastOnHover = 45;
            this.bunifuButton1.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges8.BottomLeft = true;
            borderEdges8.BottomRight = true;
            borderEdges8.TopLeft = true;
            borderEdges8.TopRight = true;
            this.bunifuButton1.CustomizableEdges = borderEdges8;
            this.bunifuButton1.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton1.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton1.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton1.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton1.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButton1.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuButton1.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton1.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton1.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton1.IconMarginLeft = 11;
            this.bunifuButton1.IconPadding = 10;
            this.bunifuButton1.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton1.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton1.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton1.IconSize = 25;
            this.bunifuButton1.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(25)))), ((int)(((byte)(91)))), ((int)(((byte)(255)))));
            this.bunifuButton1.IdleBorderRadius = 14;
            this.bunifuButton1.IdleBorderThickness = 1;
            this.bunifuButton1.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(25)))), ((int)(((byte)(91)))), ((int)(((byte)(255)))));
            this.bunifuButton1.IdleIconLeftImage = null;
            this.bunifuButton1.IdleIconRightImage = null;
            this.bunifuButton1.IndicateFocus = false;
            this.bunifuButton1.Location = new System.Drawing.Point(20, 400);
            this.bunifuButton1.Name = "bunifuButton1";
            this.bunifuButton1.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton1.OnDisabledState.BorderRadius = 14;
            this.bunifuButton1.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnDisabledState.BorderThickness = 1;
            this.bunifuButton1.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton1.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton1.OnDisabledState.IconLeftImage = null;
            this.bunifuButton1.OnDisabledState.IconRightImage = null;
            this.bunifuButton1.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(25)))), ((int)(((byte)(91)))), ((int)(((byte)(255)))));
            this.bunifuButton1.onHoverState.BorderRadius = 14;
            this.bunifuButton1.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.onHoverState.BorderThickness = 1;
            this.bunifuButton1.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(25)))), ((int)(((byte)(91)))), ((int)(((byte)(255)))));
            this.bunifuButton1.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.onHoverState.IconLeftImage = null;
            this.bunifuButton1.onHoverState.IconRightImage = null;
            this.bunifuButton1.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(25)))), ((int)(((byte)(91)))), ((int)(((byte)(255)))));
            this.bunifuButton1.OnIdleState.BorderRadius = 14;
            this.bunifuButton1.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnIdleState.BorderThickness = 1;
            this.bunifuButton1.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(25)))), ((int)(((byte)(91)))), ((int)(((byte)(255)))));
            this.bunifuButton1.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.OnIdleState.IconLeftImage = null;
            this.bunifuButton1.OnIdleState.IconRightImage = null;
            this.bunifuButton1.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(25)))), ((int)(((byte)(91)))), ((int)(((byte)(255)))));
            this.bunifuButton1.OnPressedState.BorderRadius = 14;
            this.bunifuButton1.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnPressedState.BorderThickness = 1;
            this.bunifuButton1.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(25)))), ((int)(((byte)(91)))), ((int)(((byte)(255)))));
            this.bunifuButton1.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.OnPressedState.IconLeftImage = null;
            this.bunifuButton1.OnPressedState.IconRightImage = null;
            this.bunifuButton1.Size = new System.Drawing.Size(215, 39);
            this.bunifuButton1.TabIndex = 0;
            this.bunifuButton1.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton1.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton1.TextMarginLeft = 0;
            this.bunifuButton1.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton1.UseDefaultRadiusAndThickness = true;
            this.bunifuButton1.Click += new System.EventHandler(this.bunifuButton1_Click);
            // 
            // qlmk
            // 
            this.qlmk.AllowAnimations = true;
            this.qlmk.AllowMouseEffects = true;
            this.qlmk.AllowToggling = false;
            this.qlmk.AnimationSpeed = 200;
            this.qlmk.AutoGenerateColors = false;
            this.qlmk.AutoRoundBorders = false;
            this.qlmk.AutoSizeLeftIcon = true;
            this.qlmk.AutoSizeRightIcon = true;
            this.qlmk.BackColor = System.Drawing.Color.Transparent;
            this.qlmk.BackColor1 = System.Drawing.Color.Transparent;
            this.qlmk.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("qlmk.BackgroundImage")));
            this.qlmk.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.qlmk.ButtonText = "Quản lý mật khẩu";
            this.qlmk.ButtonTextMarginLeft = 0;
            this.qlmk.ColorContrastOnClick = 45;
            this.qlmk.ColorContrastOnHover = 45;
            this.qlmk.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.qlmk.CustomizableEdges = borderEdges2;
            this.qlmk.DialogResult = System.Windows.Forms.DialogResult.None;
            this.qlmk.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.qlmk.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.qlmk.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.qlmk.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.qlmk.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.qlmk.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(62)))), ((int)(((byte)(80)))));
            this.qlmk.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.qlmk.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.qlmk.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.qlmk.IconMarginLeft = 11;
            this.qlmk.IconPadding = 10;
            this.qlmk.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.qlmk.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.qlmk.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.qlmk.IconSize = 25;
            this.qlmk.IdleBorderColor = System.Drawing.Color.Transparent;
            this.qlmk.IdleBorderRadius = 16;
            this.qlmk.IdleBorderThickness = 1;
            this.qlmk.IdleFillColor = System.Drawing.Color.Transparent;
            this.qlmk.IdleIconLeftImage = null;
            this.qlmk.IdleIconRightImage = null;
            this.qlmk.IndicateFocus = false;
            this.qlmk.Location = new System.Drawing.Point(12, 307);
            this.qlmk.Name = "qlmk";
            this.qlmk.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.qlmk.OnDisabledState.BorderRadius = 16;
            this.qlmk.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.qlmk.OnDisabledState.BorderThickness = 0;
            this.qlmk.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.qlmk.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.qlmk.OnDisabledState.IconLeftImage = null;
            this.qlmk.OnDisabledState.IconRightImage = null;
            this.qlmk.onHoverState.BorderColor = System.Drawing.Color.Transparent;
            this.qlmk.onHoverState.BorderRadius = 16;
            this.qlmk.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.qlmk.onHoverState.BorderThickness = 0;
            this.qlmk.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(244)))), ((int)(((byte)(247)))), ((int)(((byte)(248)))));
            this.qlmk.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(62)))), ((int)(((byte)(80)))));
            this.qlmk.onHoverState.IconLeftImage = null;
            this.qlmk.onHoverState.IconRightImage = null;
            this.qlmk.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.qlmk.OnIdleState.BorderRadius = 16;
            this.qlmk.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.qlmk.OnIdleState.BorderThickness = 0;
            this.qlmk.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.qlmk.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(62)))), ((int)(((byte)(80)))));
            this.qlmk.OnIdleState.IconLeftImage = null;
            this.qlmk.OnIdleState.IconRightImage = null;
            this.qlmk.OnPressedState.BorderColor = System.Drawing.Color.Transparent;
            this.qlmk.OnPressedState.BorderRadius = 16;
            this.qlmk.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.qlmk.OnPressedState.BorderThickness = 0;
            this.qlmk.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(244)))), ((int)(((byte)(247)))), ((int)(((byte)(248)))));
            this.qlmk.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(62)))), ((int)(((byte)(80)))));
            this.qlmk.OnPressedState.IconLeftImage = null;
            this.qlmk.OnPressedState.IconRightImage = null;
            this.qlmk.Size = new System.Drawing.Size(224, 34);
            this.qlmk.TabIndex = 3;
            this.qlmk.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.qlmk.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.qlmk.TextMarginLeft = 0;
            this.qlmk.TextPadding = new System.Windows.Forms.Padding(20, 0, 0, 0);
            this.qlmk.UseDefaultRadiusAndThickness = true;
            this.qlmk.Click += new System.EventHandler(this.qlmk_Click);
            // 
            // Dashboard
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(1134, 451);
            this.Controls.Add(this.mainPanel);
            this.Controls.Add(this.bunifuPanel1);
            this.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(62)))), ((int)(((byte)(80)))));
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedToolWindow;
            this.IsMdiContainer = true;
            this.MinimizeBox = false;
            this.Name = "Dashboard";
            this.Text = "Dashboard";
            this.WindowState = System.Windows.Forms.FormWindowState.Maximized;
            this.Load += new System.EventHandler(this.Dashboard_Load);
            this.bunifuPanel1.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton1;
        private Bunifu.UI.WinForms.BunifuLabel usrName;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton qlkhBtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton hoaDonBtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton loaiHangBtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton hangHoaBtn;
        private Bunifu.UI.WinForms.BunifuPanel mainPanel;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton thongKeBtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton thongTinNhom;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton qlmk;
    }
}