namespace Nhom5_TVThinhNHQHuyPNTanDVDucTNQuynh_LTNet
{
    partial class QLKhachHang
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(QLKhachHang));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.bunifuPanel1 = new Bunifu.UI.WinForms.BunifuPanel();
            this.export = new System.Windows.Forms.Label();
            this.searchTb = new Bunifu.UI.WinForms.BunifuTextBox();
            this.cancelBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.thanhphoErr = new Bunifu.UI.WinForms.BunifuLabel();
            this.quanErr = new Bunifu.UI.WinForms.BunifuLabel();
            this.dcErr = new Bunifu.UI.WinForms.BunifuLabel();
            this.tkhErr = new Bunifu.UI.WinForms.BunifuLabel();
            this.mkhErr = new Bunifu.UI.WinForms.BunifuLabel();
            this.qlkhGv = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.addBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.label1 = new System.Windows.Forms.Label();
            this.thanhphoTb = new Bunifu.UI.WinForms.BunifuTextBox();
            this.quanTb = new Bunifu.UI.WinForms.BunifuTextBox();
            this.diachiTb = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tkhTb = new Bunifu.UI.WinForms.BunifuTextBox();
            this.mkhTb = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuPanel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.qlkhGv)).BeginInit();
            this.SuspendLayout();
            // 
            // bunifuPanel1
            // 
            this.bunifuPanel1.BackgroundColor = System.Drawing.Color.Transparent;
            this.bunifuPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel1.BackgroundImage")));
            this.bunifuPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel1.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel1.BorderRadius = 3;
            this.bunifuPanel1.BorderThickness = 1;
            this.bunifuPanel1.Controls.Add(this.export);
            this.bunifuPanel1.Controls.Add(this.searchTb);
            this.bunifuPanel1.Controls.Add(this.cancelBtn);
            this.bunifuPanel1.Controls.Add(this.thanhphoErr);
            this.bunifuPanel1.Controls.Add(this.quanErr);
            this.bunifuPanel1.Controls.Add(this.dcErr);
            this.bunifuPanel1.Controls.Add(this.tkhErr);
            this.bunifuPanel1.Controls.Add(this.mkhErr);
            this.bunifuPanel1.Controls.Add(this.qlkhGv);
            this.bunifuPanel1.Controls.Add(this.addBtn);
            this.bunifuPanel1.Controls.Add(this.label1);
            this.bunifuPanel1.Controls.Add(this.thanhphoTb);
            this.bunifuPanel1.Controls.Add(this.quanTb);
            this.bunifuPanel1.Controls.Add(this.diachiTb);
            this.bunifuPanel1.Controls.Add(this.tkhTb);
            this.bunifuPanel1.Controls.Add(this.mkhTb);
            this.bunifuPanel1.Location = new System.Drawing.Point(13, 13);
            this.bunifuPanel1.Name = "bunifuPanel1";
            this.bunifuPanel1.ShowBorders = true;
            this.bunifuPanel1.Size = new System.Drawing.Size(1041, 528);
            this.bunifuPanel1.TabIndex = 0;
            // 
            // export
            // 
            this.export.AutoSize = true;
            this.export.Font = new System.Drawing.Font("Microsoft Sans Serif", 10.2F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.export.ForeColor = System.Drawing.Color.DimGray;
            this.export.Location = new System.Drawing.Point(928, 60);
            this.export.Name = "export";
            this.export.Size = new System.Drawing.Size(109, 20);
            this.export.TabIndex = 24;
            this.export.Text = "Xuất dữ liệu...";
            this.export.Click += new System.EventHandler(this.export_Click);
            this.export.MouseLeave += new System.EventHandler(this.export_MouseLeave);
            this.export.MouseHover += new System.EventHandler(this.export_MouseHover_1);
            // 
            // searchTb
            // 
            this.searchTb.AcceptsReturn = false;
            this.searchTb.AcceptsTab = false;
            this.searchTb.AnimationSpeed = 200;
            this.searchTb.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.searchTb.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.searchTb.BackColor = System.Drawing.Color.Transparent;
            this.searchTb.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("searchTb.BackgroundImage")));
            this.searchTb.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.searchTb.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.searchTb.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.searchTb.BorderColorIdle = System.Drawing.Color.Transparent;
            this.searchTb.BorderRadius = 4;
            this.searchTb.BorderThickness = 1;
            this.searchTb.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.searchTb.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.searchTb.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.searchTb.DefaultText = "";
            this.searchTb.FillColor = System.Drawing.Color.White;
            this.searchTb.HideSelection = true;
            this.searchTb.IconLeft = null;
            this.searchTb.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.searchTb.IconPadding = 10;
            this.searchTb.IconRight = null;
            this.searchTb.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.searchTb.Lines = new string[0];
            this.searchTb.Location = new System.Drawing.Point(0, 39);
            this.searchTb.MaxLength = 32767;
            this.searchTb.MinimumSize = new System.Drawing.Size(1, 1);
            this.searchTb.Modified = false;
            this.searchTb.Multiline = false;
            this.searchTb.Name = "searchTb";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.searchTb.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.searchTb.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.searchTb.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Transparent;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.searchTb.OnIdleState = stateProperties4;
            this.searchTb.Padding = new System.Windows.Forms.Padding(3);
            this.searchTb.PasswordChar = '\0';
            this.searchTb.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.searchTb.PlaceholderText = "Nhâp mã hoặc tên cần tìm...";
            this.searchTb.ReadOnly = false;
            this.searchTb.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.searchTb.SelectedText = "";
            this.searchTb.SelectionLength = 0;
            this.searchTb.SelectionStart = 0;
            this.searchTb.ShortcutsEnabled = true;
            this.searchTb.Size = new System.Drawing.Size(334, 41);
            this.searchTb.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.searchTb.TabIndex = 23;
            this.searchTb.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.searchTb.TextMarginBottom = 0;
            this.searchTb.TextMarginLeft = 3;
            this.searchTb.TextMarginTop = 0;
            this.searchTb.TextPlaceholder = "Nhâp mã hoặc tên cần tìm...";
            this.searchTb.UseSystemPasswordChar = false;
            this.searchTb.WordWrap = true;
            this.searchTb.TextChanged += new System.EventHandler(this.searchTb_TextChanged);
            // 
            // cancelBtn
            // 
            this.cancelBtn.AllowAnimations = true;
            this.cancelBtn.AllowMouseEffects = true;
            this.cancelBtn.AllowToggling = false;
            this.cancelBtn.AnimationSpeed = 200;
            this.cancelBtn.AutoGenerateColors = false;
            this.cancelBtn.AutoRoundBorders = false;
            this.cancelBtn.AutoSizeLeftIcon = true;
            this.cancelBtn.AutoSizeRightIcon = true;
            this.cancelBtn.BackColor = System.Drawing.Color.Transparent;
            this.cancelBtn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(25)))), ((int)(((byte)(91)))), ((int)(((byte)(255)))));
            this.cancelBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("cancelBtn.BackgroundImage")));
            this.cancelBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.cancelBtn.ButtonText = "Hủy";
            this.cancelBtn.ButtonTextMarginLeft = 0;
            this.cancelBtn.ColorContrastOnClick = 45;
            this.cancelBtn.ColorContrastOnHover = 45;
            this.cancelBtn.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.cancelBtn.CustomizableEdges = borderEdges1;
            this.cancelBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.cancelBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.cancelBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.cancelBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.cancelBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.cancelBtn.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.cancelBtn.ForeColor = System.Drawing.Color.White;
            this.cancelBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.cancelBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.cancelBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.cancelBtn.IconMarginLeft = 11;
            this.cancelBtn.IconPadding = 10;
            this.cancelBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.cancelBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.cancelBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.cancelBtn.IconSize = 25;
            this.cancelBtn.IdleBorderColor = System.Drawing.Color.Transparent;
            this.cancelBtn.IdleBorderRadius = 16;
            this.cancelBtn.IdleBorderThickness = 1;
            this.cancelBtn.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(25)))), ((int)(((byte)(91)))), ((int)(((byte)(255)))));
            this.cancelBtn.IdleIconLeftImage = null;
            this.cancelBtn.IdleIconRightImage = null;
            this.cancelBtn.IndicateFocus = false;
            this.cancelBtn.Location = new System.Drawing.Point(891, 461);
            this.cancelBtn.Margin = new System.Windows.Forms.Padding(4);
            this.cancelBtn.Name = "cancelBtn";
            this.cancelBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.cancelBtn.OnDisabledState.BorderRadius = 16;
            this.cancelBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.cancelBtn.OnDisabledState.BorderThickness = 1;
            this.cancelBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.cancelBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.cancelBtn.OnDisabledState.IconLeftImage = null;
            this.cancelBtn.OnDisabledState.IconRightImage = null;
            this.cancelBtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.cancelBtn.onHoverState.BorderRadius = 16;
            this.cancelBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.cancelBtn.onHoverState.BorderThickness = 1;
            this.cancelBtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.cancelBtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.cancelBtn.onHoverState.IconLeftImage = null;
            this.cancelBtn.onHoverState.IconRightImage = null;
            this.cancelBtn.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.cancelBtn.OnIdleState.BorderRadius = 16;
            this.cancelBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.cancelBtn.OnIdleState.BorderThickness = 1;
            this.cancelBtn.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(25)))), ((int)(((byte)(91)))), ((int)(((byte)(255)))));
            this.cancelBtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.cancelBtn.OnIdleState.IconLeftImage = null;
            this.cancelBtn.OnIdleState.IconRightImage = null;
            this.cancelBtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.cancelBtn.OnPressedState.BorderRadius = 16;
            this.cancelBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.cancelBtn.OnPressedState.BorderThickness = 1;
            this.cancelBtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.cancelBtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.cancelBtn.OnPressedState.IconLeftImage = null;
            this.cancelBtn.OnPressedState.IconRightImage = null;
            this.cancelBtn.Size = new System.Drawing.Size(146, 41);
            this.cancelBtn.TabIndex = 22;
            this.cancelBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.cancelBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.cancelBtn.TextMarginLeft = 0;
            this.cancelBtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.cancelBtn.UseDefaultRadiusAndThickness = true;
            this.cancelBtn.Click += new System.EventHandler(this.cancelBtn_Click);
            // 
            // thanhphoErr
            // 
            this.thanhphoErr.AccessibleRole = System.Windows.Forms.AccessibleRole.TitleBar;
            this.thanhphoErr.AllowParentOverrides = false;
            this.thanhphoErr.AutoEllipsis = false;
            this.thanhphoErr.Cursor = System.Windows.Forms.Cursors.Default;
            this.thanhphoErr.CursorType = System.Windows.Forms.Cursors.Default;
            this.thanhphoErr.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.thanhphoErr.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(71)))), ((int)(((byte)(87)))));
            this.thanhphoErr.Location = new System.Drawing.Point(715, 425);
            this.thanhphoErr.Margin = new System.Windows.Forms.Padding(4);
            this.thanhphoErr.Name = "thanhphoErr";
            this.thanhphoErr.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.thanhphoErr.Size = new System.Drawing.Size(0, 0);
            this.thanhphoErr.TabIndex = 21;
            this.thanhphoErr.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.thanhphoErr.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // quanErr
            // 
            this.quanErr.AccessibleRole = System.Windows.Forms.AccessibleRole.TitleBar;
            this.quanErr.AllowParentOverrides = false;
            this.quanErr.AutoEllipsis = false;
            this.quanErr.Cursor = System.Windows.Forms.Cursors.Default;
            this.quanErr.CursorType = System.Windows.Forms.Cursors.Default;
            this.quanErr.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.quanErr.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(71)))), ((int)(((byte)(87)))));
            this.quanErr.Location = new System.Drawing.Point(367, 509);
            this.quanErr.Margin = new System.Windows.Forms.Padding(4);
            this.quanErr.Name = "quanErr";
            this.quanErr.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.quanErr.Size = new System.Drawing.Size(0, 0);
            this.quanErr.TabIndex = 20;
            this.quanErr.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.quanErr.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // dcErr
            // 
            this.dcErr.AccessibleRole = System.Windows.Forms.AccessibleRole.TitleBar;
            this.dcErr.AllowParentOverrides = false;
            this.dcErr.AutoEllipsis = false;
            this.dcErr.Cursor = System.Windows.Forms.Cursors.Default;
            this.dcErr.CursorType = System.Windows.Forms.Cursors.Default;
            this.dcErr.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.dcErr.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(71)))), ((int)(((byte)(87)))));
            this.dcErr.Location = new System.Drawing.Point(367, 425);
            this.dcErr.Margin = new System.Windows.Forms.Padding(4);
            this.dcErr.Name = "dcErr";
            this.dcErr.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.dcErr.Size = new System.Drawing.Size(0, 0);
            this.dcErr.TabIndex = 19;
            this.dcErr.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.dcErr.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // tkhErr
            // 
            this.tkhErr.AccessibleRole = System.Windows.Forms.AccessibleRole.TitleBar;
            this.tkhErr.AllowParentOverrides = false;
            this.tkhErr.AutoEllipsis = false;
            this.tkhErr.Cursor = System.Windows.Forms.Cursors.Default;
            this.tkhErr.CursorType = System.Windows.Forms.Cursors.Default;
            this.tkhErr.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.tkhErr.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(71)))), ((int)(((byte)(87)))));
            this.tkhErr.Location = new System.Drawing.Point(15, 509);
            this.tkhErr.Margin = new System.Windows.Forms.Padding(4);
            this.tkhErr.Name = "tkhErr";
            this.tkhErr.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.tkhErr.Size = new System.Drawing.Size(0, 0);
            this.tkhErr.TabIndex = 18;
            this.tkhErr.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.tkhErr.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // mkhErr
            // 
            this.mkhErr.AccessibleRole = System.Windows.Forms.AccessibleRole.TitleBar;
            this.mkhErr.AllowParentOverrides = false;
            this.mkhErr.AutoEllipsis = false;
            this.mkhErr.Cursor = System.Windows.Forms.Cursors.Default;
            this.mkhErr.CursorType = System.Windows.Forms.Cursors.Default;
            this.mkhErr.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.mkhErr.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(71)))), ((int)(((byte)(87)))));
            this.mkhErr.Location = new System.Drawing.Point(15, 425);
            this.mkhErr.Margin = new System.Windows.Forms.Padding(4);
            this.mkhErr.Name = "mkhErr";
            this.mkhErr.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.mkhErr.Size = new System.Drawing.Size(0, 0);
            this.mkhErr.TabIndex = 17;
            this.mkhErr.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.mkhErr.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // qlkhGv
            // 
            this.qlkhGv.AllowCustomTheming = false;
            this.qlkhGv.AllowUserToAddRows = false;
            this.qlkhGv.AllowUserToDeleteRows = false;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle1.ForeColor = System.Drawing.Color.Black;
            this.qlkhGv.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            this.qlkhGv.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.qlkhGv.BackgroundColor = System.Drawing.Color.White;
            this.qlkhGv.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.qlkhGv.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.qlkhGv.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.DodgerBlue;
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.qlkhGv.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.qlkhGv.ColumnHeadersHeight = 40;
            this.qlkhGv.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            this.qlkhGv.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.qlkhGv.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.qlkhGv.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.qlkhGv.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.qlkhGv.CurrentTheme.BackColor = System.Drawing.Color.White;
            this.qlkhGv.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.qlkhGv.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.DodgerBlue;
            this.qlkhGv.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.qlkhGv.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.qlkhGv.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            this.qlkhGv.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.qlkhGv.CurrentTheme.Name = null;
            this.qlkhGv.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.White;
            this.qlkhGv.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.qlkhGv.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.qlkhGv.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.qlkhGv.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.qlkhGv.DefaultCellStyle = dataGridViewCellStyle3;
            this.qlkhGv.EnableHeadersVisualStyles = false;
            this.qlkhGv.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.qlkhGv.HeaderBackColor = System.Drawing.Color.DodgerBlue;
            this.qlkhGv.HeaderBgColor = System.Drawing.Color.Empty;
            this.qlkhGv.HeaderForeColor = System.Drawing.Color.White;
            this.qlkhGv.Location = new System.Drawing.Point(3, 86);
            this.qlkhGv.MultiSelect = false;
            this.qlkhGv.Name = "qlkhGv";
            this.qlkhGv.ReadOnly = true;
            this.qlkhGv.RowHeadersVisible = false;
            this.qlkhGv.RowHeadersWidth = 100;
            this.qlkhGv.RowHeadersWidthSizeMode = System.Windows.Forms.DataGridViewRowHeadersWidthSizeMode.DisableResizing;
            this.qlkhGv.RowTemplate.Height = 40;
            this.qlkhGv.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.qlkhGv.Size = new System.Drawing.Size(1035, 272);
            this.qlkhGv.TabIndex = 10;
            this.qlkhGv.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
            this.qlkhGv.CellClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.qlkhGv_CellClick);
            this.qlkhGv.CellContentClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.qlkhGv_CellContentClick);
            // 
            // addBtn
            // 
            this.addBtn.AllowAnimations = true;
            this.addBtn.AllowMouseEffects = true;
            this.addBtn.AllowToggling = false;
            this.addBtn.AnimationSpeed = 200;
            this.addBtn.AutoGenerateColors = false;
            this.addBtn.AutoRoundBorders = false;
            this.addBtn.AutoSizeLeftIcon = true;
            this.addBtn.AutoSizeRightIcon = true;
            this.addBtn.BackColor = System.Drawing.Color.Transparent;
            this.addBtn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(25)))), ((int)(((byte)(91)))), ((int)(((byte)(255)))));
            this.addBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("addBtn.BackgroundImage")));
            this.addBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.addBtn.ButtonText = "Lưu";
            this.addBtn.ButtonTextMarginLeft = 0;
            this.addBtn.ColorContrastOnClick = 45;
            this.addBtn.ColorContrastOnHover = 45;
            this.addBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.addBtn.CustomizableEdges = borderEdges2;
            this.addBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.addBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.addBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.addBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.addBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.addBtn.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.addBtn.ForeColor = System.Drawing.Color.White;
            this.addBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.addBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.addBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.addBtn.IconMarginLeft = 11;
            this.addBtn.IconPadding = 10;
            this.addBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.addBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.addBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.addBtn.IconSize = 25;
            this.addBtn.IdleBorderColor = System.Drawing.Color.Transparent;
            this.addBtn.IdleBorderRadius = 16;
            this.addBtn.IdleBorderThickness = 1;
            this.addBtn.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(25)))), ((int)(((byte)(91)))), ((int)(((byte)(255)))));
            this.addBtn.IdleIconLeftImage = null;
            this.addBtn.IdleIconRightImage = null;
            this.addBtn.IndicateFocus = false;
            this.addBtn.Location = new System.Drawing.Point(704, 461);
            this.addBtn.Margin = new System.Windows.Forms.Padding(4);
            this.addBtn.Name = "addBtn";
            this.addBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.addBtn.OnDisabledState.BorderRadius = 16;
            this.addBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.addBtn.OnDisabledState.BorderThickness = 1;
            this.addBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.addBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.addBtn.OnDisabledState.IconLeftImage = null;
            this.addBtn.OnDisabledState.IconRightImage = null;
            this.addBtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.addBtn.onHoverState.BorderRadius = 16;
            this.addBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.addBtn.onHoverState.BorderThickness = 1;
            this.addBtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.addBtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.addBtn.onHoverState.IconLeftImage = null;
            this.addBtn.onHoverState.IconRightImage = null;
            this.addBtn.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.addBtn.OnIdleState.BorderRadius = 16;
            this.addBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.addBtn.OnIdleState.BorderThickness = 1;
            this.addBtn.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(25)))), ((int)(((byte)(91)))), ((int)(((byte)(255)))));
            this.addBtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.addBtn.OnIdleState.IconLeftImage = null;
            this.addBtn.OnIdleState.IconRightImage = null;
            this.addBtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.addBtn.OnPressedState.BorderRadius = 16;
            this.addBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.addBtn.OnPressedState.BorderThickness = 1;
            this.addBtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.addBtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.addBtn.OnPressedState.IconLeftImage = null;
            this.addBtn.OnPressedState.IconRightImage = null;
            this.addBtn.Size = new System.Drawing.Size(146, 41);
            this.addBtn.TabIndex = 9;
            this.addBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.addBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.addBtn.TextMarginLeft = 0;
            this.addBtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.addBtn.UseDefaultRadiusAndThickness = true;
            this.addBtn.Click += new System.EventHandler(this.addBtn_Click);
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Microsoft Sans Serif", 13.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(25)))), ((int)(((byte)(91)))), ((int)(((byte)(255)))));
            this.label1.Location = new System.Drawing.Point(378, 0);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(297, 29);
            this.label1.TabIndex = 7;
            this.label1.Text = "QUẢN LÝ KHÁCH HÀNG";
            // 
            // thanhphoTb
            // 
            this.thanhphoTb.AcceptsReturn = false;
            this.thanhphoTb.AcceptsTab = false;
            this.thanhphoTb.AnimationSpeed = 200;
            this.thanhphoTb.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.thanhphoTb.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.thanhphoTb.BackColor = System.Drawing.Color.Transparent;
            this.thanhphoTb.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("thanhphoTb.BackgroundImage")));
            this.thanhphoTb.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.thanhphoTb.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.thanhphoTb.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.thanhphoTb.BorderColorIdle = System.Drawing.Color.Silver;
            this.thanhphoTb.BorderRadius = 16;
            this.thanhphoTb.BorderThickness = 1;
            this.thanhphoTb.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.thanhphoTb.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.thanhphoTb.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.thanhphoTb.DefaultText = "";
            this.thanhphoTb.FillColor = System.Drawing.Color.White;
            this.thanhphoTb.HideSelection = true;
            this.thanhphoTb.IconLeft = null;
            this.thanhphoTb.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.thanhphoTb.IconPadding = 10;
            this.thanhphoTb.IconRight = null;
            this.thanhphoTb.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.thanhphoTb.Lines = new string[0];
            this.thanhphoTb.Location = new System.Drawing.Point(704, 377);
            this.thanhphoTb.MaxLength = 32767;
            this.thanhphoTb.MinimumSize = new System.Drawing.Size(1, 1);
            this.thanhphoTb.Modified = false;
            this.thanhphoTb.Multiline = false;
            this.thanhphoTb.Name = "thanhphoTb";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.thanhphoTb.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.thanhphoTb.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.thanhphoTb.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.thanhphoTb.OnIdleState = stateProperties8;
            this.thanhphoTb.Padding = new System.Windows.Forms.Padding(3);
            this.thanhphoTb.PasswordChar = '\0';
            this.thanhphoTb.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.thanhphoTb.PlaceholderText = "Tỉnh/ Thành phố";
            this.thanhphoTb.ReadOnly = false;
            this.thanhphoTb.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.thanhphoTb.SelectedText = "";
            this.thanhphoTb.SelectionLength = 0;
            this.thanhphoTb.SelectionStart = 0;
            this.thanhphoTb.ShortcutsEnabled = true;
            this.thanhphoTb.Size = new System.Drawing.Size(334, 41);
            this.thanhphoTb.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.thanhphoTb.TabIndex = 6;
            this.thanhphoTb.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.thanhphoTb.TextMarginBottom = 0;
            this.thanhphoTb.TextMarginLeft = 3;
            this.thanhphoTb.TextMarginTop = 0;
            this.thanhphoTb.TextPlaceholder = "Tỉnh/ Thành phố";
            this.thanhphoTb.UseSystemPasswordChar = false;
            this.thanhphoTb.WordWrap = true;
            this.thanhphoTb.MouseClick += new System.Windows.Forms.MouseEventHandler(this.thanhphoTb_MouseClick);
            // 
            // quanTb
            // 
            this.quanTb.AcceptsReturn = false;
            this.quanTb.AcceptsTab = false;
            this.quanTb.AnimationSpeed = 200;
            this.quanTb.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.quanTb.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.quanTb.BackColor = System.Drawing.Color.Transparent;
            this.quanTb.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("quanTb.BackgroundImage")));
            this.quanTb.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.quanTb.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.quanTb.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.quanTb.BorderColorIdle = System.Drawing.Color.Silver;
            this.quanTb.BorderRadius = 16;
            this.quanTb.BorderThickness = 1;
            this.quanTb.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.quanTb.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.quanTb.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.quanTb.DefaultText = "";
            this.quanTb.FillColor = System.Drawing.Color.White;
            this.quanTb.HideSelection = true;
            this.quanTb.IconLeft = null;
            this.quanTb.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.quanTb.IconPadding = 10;
            this.quanTb.IconRight = null;
            this.quanTb.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.quanTb.Lines = new string[0];
            this.quanTb.Location = new System.Drawing.Point(355, 461);
            this.quanTb.MaxLength = 32767;
            this.quanTb.MinimumSize = new System.Drawing.Size(1, 1);
            this.quanTb.Modified = false;
            this.quanTb.Multiline = false;
            this.quanTb.Name = "quanTb";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.quanTb.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.quanTb.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.quanTb.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.quanTb.OnIdleState = stateProperties12;
            this.quanTb.Padding = new System.Windows.Forms.Padding(3);
            this.quanTb.PasswordChar = '\0';
            this.quanTb.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.quanTb.PlaceholderText = "Quận/ Huyện";
            this.quanTb.ReadOnly = false;
            this.quanTb.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.quanTb.SelectedText = "";
            this.quanTb.SelectionLength = 0;
            this.quanTb.SelectionStart = 0;
            this.quanTb.ShortcutsEnabled = true;
            this.quanTb.Size = new System.Drawing.Size(334, 41);
            this.quanTb.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.quanTb.TabIndex = 5;
            this.quanTb.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.quanTb.TextMarginBottom = 0;
            this.quanTb.TextMarginLeft = 3;
            this.quanTb.TextMarginTop = 0;
            this.quanTb.TextPlaceholder = "Quận/ Huyện";
            this.quanTb.UseSystemPasswordChar = false;
            this.quanTb.WordWrap = true;
            this.quanTb.MouseClick += new System.Windows.Forms.MouseEventHandler(this.quanTb_MouseClick);
            // 
            // diachiTb
            // 
            this.diachiTb.AcceptsReturn = false;
            this.diachiTb.AcceptsTab = false;
            this.diachiTb.AnimationSpeed = 200;
            this.diachiTb.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.diachiTb.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.diachiTb.BackColor = System.Drawing.Color.Transparent;
            this.diachiTb.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("diachiTb.BackgroundImage")));
            this.diachiTb.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.diachiTb.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.diachiTb.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.diachiTb.BorderColorIdle = System.Drawing.Color.Silver;
            this.diachiTb.BorderRadius = 16;
            this.diachiTb.BorderThickness = 1;
            this.diachiTb.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.diachiTb.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.diachiTb.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.diachiTb.DefaultText = "";
            this.diachiTb.FillColor = System.Drawing.Color.White;
            this.diachiTb.HideSelection = true;
            this.diachiTb.IconLeft = null;
            this.diachiTb.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.diachiTb.IconPadding = 10;
            this.diachiTb.IconRight = null;
            this.diachiTb.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.diachiTb.Lines = new string[0];
            this.diachiTb.Location = new System.Drawing.Point(355, 377);
            this.diachiTb.MaxLength = 32767;
            this.diachiTb.MinimumSize = new System.Drawing.Size(1, 1);
            this.diachiTb.Modified = false;
            this.diachiTb.Multiline = false;
            this.diachiTb.Name = "diachiTb";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.diachiTb.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.diachiTb.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.diachiTb.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.diachiTb.OnIdleState = stateProperties16;
            this.diachiTb.Padding = new System.Windows.Forms.Padding(3);
            this.diachiTb.PasswordChar = '\0';
            this.diachiTb.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.diachiTb.PlaceholderText = "Phường/ Xã";
            this.diachiTb.ReadOnly = false;
            this.diachiTb.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.diachiTb.SelectedText = "";
            this.diachiTb.SelectionLength = 0;
            this.diachiTb.SelectionStart = 0;
            this.diachiTb.ShortcutsEnabled = true;
            this.diachiTb.Size = new System.Drawing.Size(334, 41);
            this.diachiTb.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.diachiTb.TabIndex = 4;
            this.diachiTb.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.diachiTb.TextMarginBottom = 0;
            this.diachiTb.TextMarginLeft = 3;
            this.diachiTb.TextMarginTop = 0;
            this.diachiTb.TextPlaceholder = "Phường/ Xã";
            this.diachiTb.UseSystemPasswordChar = false;
            this.diachiTb.WordWrap = true;
            this.diachiTb.MouseClick += new System.Windows.Forms.MouseEventHandler(this.diachiTb_MouseClick);
            // 
            // tkhTb
            // 
            this.tkhTb.AcceptsReturn = false;
            this.tkhTb.AcceptsTab = false;
            this.tkhTb.AnimationSpeed = 200;
            this.tkhTb.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tkhTb.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tkhTb.BackColor = System.Drawing.Color.Transparent;
            this.tkhTb.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tkhTb.BackgroundImage")));
            this.tkhTb.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tkhTb.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tkhTb.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tkhTb.BorderColorIdle = System.Drawing.Color.Silver;
            this.tkhTb.BorderRadius = 16;
            this.tkhTb.BorderThickness = 1;
            this.tkhTb.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tkhTb.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tkhTb.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.tkhTb.DefaultText = "";
            this.tkhTb.FillColor = System.Drawing.Color.White;
            this.tkhTb.HideSelection = true;
            this.tkhTb.IconLeft = null;
            this.tkhTb.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tkhTb.IconPadding = 10;
            this.tkhTb.IconRight = null;
            this.tkhTb.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tkhTb.Lines = new string[0];
            this.tkhTb.Location = new System.Drawing.Point(3, 461);
            this.tkhTb.MaxLength = 32767;
            this.tkhTb.MinimumSize = new System.Drawing.Size(1, 1);
            this.tkhTb.Modified = false;
            this.tkhTb.Multiline = false;
            this.tkhTb.Name = "tkhTb";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tkhTb.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tkhTb.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tkhTb.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tkhTb.OnIdleState = stateProperties20;
            this.tkhTb.Padding = new System.Windows.Forms.Padding(3);
            this.tkhTb.PasswordChar = '\0';
            this.tkhTb.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tkhTb.PlaceholderText = "Tên khách hàng";
            this.tkhTb.ReadOnly = false;
            this.tkhTb.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tkhTb.SelectedText = "";
            this.tkhTb.SelectionLength = 0;
            this.tkhTb.SelectionStart = 0;
            this.tkhTb.ShortcutsEnabled = true;
            this.tkhTb.Size = new System.Drawing.Size(334, 41);
            this.tkhTb.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tkhTb.TabIndex = 3;
            this.tkhTb.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tkhTb.TextMarginBottom = 0;
            this.tkhTb.TextMarginLeft = 3;
            this.tkhTb.TextMarginTop = 0;
            this.tkhTb.TextPlaceholder = "Tên khách hàng";
            this.tkhTb.UseSystemPasswordChar = false;
            this.tkhTb.WordWrap = true;
            this.tkhTb.MouseClick += new System.Windows.Forms.MouseEventHandler(this.tkhTb_MouseClick);
            // 
            // mkhTb
            // 
            this.mkhTb.AcceptsReturn = false;
            this.mkhTb.AcceptsTab = false;
            this.mkhTb.AnimationSpeed = 200;
            this.mkhTb.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.mkhTb.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.mkhTb.BackColor = System.Drawing.Color.Transparent;
            this.mkhTb.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("mkhTb.BackgroundImage")));
            this.mkhTb.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.mkhTb.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.mkhTb.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.mkhTb.BorderColorIdle = System.Drawing.Color.Silver;
            this.mkhTb.BorderRadius = 16;
            this.mkhTb.BorderThickness = 1;
            this.mkhTb.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.mkhTb.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.mkhTb.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.mkhTb.DefaultText = "";
            this.mkhTb.FillColor = System.Drawing.Color.White;
            this.mkhTb.HideSelection = true;
            this.mkhTb.IconLeft = null;
            this.mkhTb.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.mkhTb.IconPadding = 10;
            this.mkhTb.IconRight = null;
            this.mkhTb.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.mkhTb.Lines = new string[0];
            this.mkhTb.Location = new System.Drawing.Point(3, 377);
            this.mkhTb.MaxLength = 32767;
            this.mkhTb.MinimumSize = new System.Drawing.Size(1, 1);
            this.mkhTb.Modified = false;
            this.mkhTb.Multiline = false;
            this.mkhTb.Name = "mkhTb";
            stateProperties21.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.mkhTb.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.mkhTb.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.mkhTb.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.mkhTb.OnIdleState = stateProperties24;
            this.mkhTb.Padding = new System.Windows.Forms.Padding(3);
            this.mkhTb.PasswordChar = '\0';
            this.mkhTb.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.mkhTb.PlaceholderText = "Mã khách hàng";
            this.mkhTb.ReadOnly = false;
            this.mkhTb.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.mkhTb.SelectedText = "";
            this.mkhTb.SelectionLength = 0;
            this.mkhTb.SelectionStart = 0;
            this.mkhTb.ShortcutsEnabled = true;
            this.mkhTb.Size = new System.Drawing.Size(334, 41);
            this.mkhTb.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.mkhTb.TabIndex = 2;
            this.mkhTb.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.mkhTb.TextMarginBottom = 0;
            this.mkhTb.TextMarginLeft = 3;
            this.mkhTb.TextMarginTop = 0;
            this.mkhTb.TextPlaceholder = "Mã khách hàng";
            this.mkhTb.UseSystemPasswordChar = false;
            this.mkhTb.WordWrap = true;
            this.mkhTb.MouseClick += new System.Windows.Forms.MouseEventHandler(this.mkhTb_MouseClick);
            // 
            // QLKhachHang
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(1067, 554);
            this.Controls.Add(this.bunifuPanel1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Margin = new System.Windows.Forms.Padding(4);
            this.Name = "QLKhachHang";
            this.Padding = new System.Windows.Forms.Padding(10);
            this.Text = "QLKhachHang";
            this.Load += new System.EventHandler(this.QLKhachHang_Load);
            this.bunifuPanel1.ResumeLayout(false);
            this.bunifuPanel1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.qlkhGv)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel1;
        private Bunifu.UI.WinForms.BunifuTextBox quanTb;
        private Bunifu.UI.WinForms.BunifuTextBox diachiTb;
        private Bunifu.UI.WinForms.BunifuTextBox tkhTb;
        private Bunifu.UI.WinForms.BunifuTextBox mkhTb;
        private Bunifu.UI.WinForms.BunifuTextBox thanhphoTb;
        private System.Windows.Forms.Label label1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton addBtn;
        private Bunifu.UI.WinForms.BunifuDataGridView qlkhGv;
        private Bunifu.UI.WinForms.BunifuLabel dcErr;
        private Bunifu.UI.WinForms.BunifuLabel tkhErr;
        private Bunifu.UI.WinForms.BunifuLabel mkhErr;
        private Bunifu.UI.WinForms.BunifuLabel thanhphoErr;
        private Bunifu.UI.WinForms.BunifuLabel quanErr;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton cancelBtn;
        private Bunifu.UI.WinForms.BunifuTextBox searchTb;
        private System.Windows.Forms.Label export;
    }
}